const motivationalPhrases = [
    "Believe in yourself and all that you are.",
    "You are capable of amazing things.",
    "Dream big and dare to fail.",
    "Stay focused and never give up.",
    "You are stronger than you think.",
    "Success is not final, failure is not fatal",
    "You are unstoppable.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "You are enough just as you are.",
    "Strive for progress, not perfection.",
    "The journey of a thousand miles begins with a single step.",
    "Nothing worth having comes easy.",
    "You are the architect of your own destiny.",
    "Difficult roads often lead to beautiful destinations.",
    "Every accomplishment starts with the decision to try.",
    "You are capable of more than you know.",
    "Embrace the uncertainty.",
    "You are one step closer with every choice you make.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Your potential is endless.",
    "You are stronger than your excuses.",
    "Every setback is a setup for a comeback.",
    "Positive action, positive results.",
    "Difficult roads lead to beauty.",
    "Every accomplishment starts with a choice.",
    "Deserving of good things.",
    "One step closer with every choice.",
    "Fearless pursuit of passion.",
    "Endless potential.",
    "No excuses.",
    "We believe in you.",
];

export { motivationalPhrases };
