const praiseSentences = [
    "You're awesome!",
    "Great job!",
    "You're amazing!",
    "Keep up the good work!",
    "Fantastic effort!",
    "You're doing great!",
    "Well done!",
    "Incredible work!",
    "Bravo!",
    "Outstanding performance!",
    "You're exceptional!",
    "Terrific job!",
    "Impressive work!",
    "You're a star!",
    "Excellent job!",
    "You're fantastic!",
    "Keep it up!",
    "Superb effort!",
    "You're remarkable!",
    "Amazing work!",
    "You're outstanding!",
    "Top-notch performance!",
    "You're phenomenal!",
    "Splendid job!",
    "You're fabulous!",
    "Remarkable job!",
    "You're doing fantastic!",
    "Exceptional work!",
    "You're terrific!",
    "Great going!",
    // Add more as needed
];

export { praiseSentences };
